### ISSUE TITLE
Data still depends on global.yaml

### ISSUE THREAD

**Issue by zakilur** [greymatter-io/helm-charts#803]
Data is labeled as an optional component and has been segmented off. However, installing data is still dependent on the below setting in the `global.yaml` file. If this setting is `false` (the default value), data will not install properly. This dependency likely needs to be removed.

```
  data:
    # whether to install an external data
    external:
      enabled: true
```
