### ISSUE TITLE
look to add links between configmaps and deployments

### ISSUE THREAD

**Issue by chrisbsmith** [greymatter-io/helm-charts#938]
we have several services that are dependent on configmaps; however, kubernetes does not automatically bounce a pod when a configmap is changed. 

there appears to be a way to do with this sha256 sum or other options.  

https://stackoverflow.com/a/54582812/14176651

```
kind: Deployment
spec:
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
```
